import type { WorkerProfile, Job, CustomerAddress } from './types';

export const primarySkills = [
  'Masonry',
  'Carpentry',
  'Plumbing',
  'Electrical',
  'Painting',
  'Welding',
  'General Labour',
];

export const mockWorkers: WorkerProfile[] = [
  {
    id: 'w1',
    name: 'Ramesh Kumar',
    mobileNumber: '+919876543210',
    experience: '10 yrs exp',
    location: 'Delhi, India',
    primarySkills: ['Masonry'],
    secondarySkills: 'Tiling, waterproofing',
    desiredDailyWage: 800,
    language: 'hi',
    avatarUrl: 'https://picsum.photos/seed/ramesh/200/200',
    rating: 4.5,
  },
  {
    id: 'w2',
    name: 'Sita Devi',
    mobileNumber: '+919876543211',
    experience: '5 yrs exp',
    location: 'Mumbai, India',
    primarySkills: ['Painting'],
    secondarySkills: 'Furniture polishing, minor repairs',
    desiredDailyWage: 900,
    language: 'en',
    avatarUrl: 'https://picsum.photos/seed/sita/200/200',
    rating: 4.8,
  },
  {
    id: 'w3',
    name: 'Priya Sharma',
    mobileNumber: '+919876543212',
    experience: '12 yrs exp',
    location: 'Delhi, India',
    primarySkills: ['Plumber'],
    secondarySkills: 'Appliance installation',
    desiredDailyWage: 700,
    language: 'en',
    avatarUrl: 'https://picsum.photos/seed/priya/200/200',
    rating: 4.9,
  },
  {
    id: 'w4',
    name: 'Bikash Das',
    mobileNumber: '+919876543213',
    experience: '5+ years',
    location: 'Kolkata, India',
    primarySkills: ['Painting'],
    secondarySkills: 'Wall putty, design painting',
    desiredDailyWage: 850,
    language: 'bn',
    avatarUrl: 'https://picsum.photos/seed/w4/200/200',
    rating: 4.2
  },
  {
    id: 'w5',
    name: 'Vijay Verma',
    mobileNumber: '+919876543214',
    experience: '1-3 years',
    location: 'Mumbai, India',
    primarySkills: ['General Labour'],
    secondarySkills: 'Site cleaning, material handling',
    desiredDailyWage: 500,
    language: 'hi',
    avatarUrl: 'https://picsum.photos/seed/w5/200/200',
    rating: 4.0
  },
];

export const mockJobs: Job[] = [
  {
    id: 'j1',
    title: 'House Renovation Work',
    description: 'Need skilled labour for a full house renovation. Includes masonry, plumbing, and electrical work. Project duration is approximately 2 months.',
    location: 'Delhi, India',
    wage: 1000,
    skills: ['Masonry', 'Plumbing', 'Electrical'],
    customerId: 'c1',
    status: 'open',
  },
  {
    id: 'j2',
    title: 'Apartment Painting',
    description: 'Looking for an experienced painter to paint a 2BHK apartment. All materials will be provided. Work needs to be completed within a week.',
    location: 'Kolkata, India',
    wage: 900,
    skills: ['Painting'],
    customerId: 'c2',
    status: 'open',
  },
  {
    id: 'j3',
    title: 'Office Furniture Assembly',
    description: 'Need a carpenter to assemble new office furniture. Should be quick and efficient.',
    location: 'Mumbai, India',
    wage: 950,
    skills: ['Carpentry'],
    customerId: 'c1',
    status: 'active',
  },
    {
    id: 'j4',
    title: 'Site cleanup',
    description: 'Requires a team of 5 general laborers for a construction site cleanup project. The work will involve debris removal and site organization.',
    location: 'Delhi, India',
    wage: 600,
    skills: ['General Labour'],
    customerId: 'c3',
    status: 'completed',
  },
];

export const mockCustomerAddresses: CustomerAddress[] = [
  { id: 'addr1', address: '123 Business Rd, Connaught Place, New Delhi, Delhi 110001, India' },
  { id: 'addr2', address: '456 Home Ave, Sector 29, Gurugram, Haryana 122022, India' },
];
